<template><p>在做公司網站時，有遇到想要把a網站的內容在b網站上顯示，本來我以前都是用iframe來處理，但有時候想要抓取的並不是整個頁面，使用iframe就比較不符合需求，所以嘗試改成使用php來抓取b網站上的特定內容！</p>
<h2 id="取得指定網頁內的所有圖片" tabindex="-1"><a class="header-anchor" href="#取得指定網頁內的所有圖片" aria-hidden="true">#</a> 取得指定網頁內的所有圖片</h2>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token comment">//取得指定位址的內容，並儲存至text</span>
<span class="token variable">$text</span><span class="token operator">=</span><span class="token function">file_get_contents</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'https://alan-zl.github.io/Blogs/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//取得所有img標籤，並儲存至二維陣列match</span>
<span class="token function">preg_match_all</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'#&lt;img[^>]*>#i'</span><span class="token punctuation">,</span> <span class="token variable">$text</span><span class="token punctuation">,</span> <span class="token variable">$match</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//印出match</span>
<span class="token function">print_r</span><span class="token punctuation">(</span><span class="token variable">$match</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="取得指定網頁內的第一張圖片" tabindex="-1"><a class="header-anchor" href="#取得指定網頁內的第一張圖片" aria-hidden="true">#</a> 取得指定網頁內的第一張圖片</h2>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token comment">//取得指定位址的內容，並儲存至text</span>
<span class="token variable">$text</span><span class="token operator">=</span><span class="token function">file_get_contents</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'https://alan-zl.github.io/Blogs/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//取得第一個img標籤，並儲存至陣列match（regex語法與上述同義）</span>
<span class="token function">preg_match</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'/&lt;img[^>]*>/Ui'</span><span class="token punctuation">,</span> <span class="token variable">$text</span><span class="token punctuation">,</span> <span class="token variable">$match</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//印出match</span>
<span class="token function">print_r</span><span class="token punctuation">(</span><span class="token variable">$match</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="取得指定網頁內的特定div區塊-藉由id判斷" tabindex="-1"><a class="header-anchor" href="#取得指定網頁內的特定div區塊-藉由id判斷" aria-hidden="true">#</a> 取得指定網頁內的特定div區塊（藉由id判斷）</h2>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token comment">//取得指定位址的內容，並儲存至text</span>
<span class="token variable">$text</span><span class="token operator">=</span><span class="token function">file_get_contents</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'https://alan-zl.github.io/Blogs/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//去除換行及空白字元（序列化內容才需使用）</span>
<span class="token variable">$text</span><span class="token operator">=</span><span class="token function">str_replace</span><span class="token punctuation">(</span><span class="token keyword">array</span><span class="token punctuation">(</span><span class="token string double-quoted-string">"\r"</span><span class="token punctuation">,</span><span class="token string double-quoted-string">"\n"</span><span class="token punctuation">,</span><span class="token string double-quoted-string">"\t"</span><span class="token punctuation">,</span><span class="token string double-quoted-string">"\s"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">''</span><span class="token punctuation">,</span> <span class="token variable">$text</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  

<span class="token comment">//取出div標籤且id為PostContent的內容，並儲存至陣列match</span>
<span class="token function">preg_match</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'/&lt;div[^>]*id="PostContent"[^>]*>(.*?) &lt;\/div>/si'</span><span class="token punctuation">,</span><span class="token variable">$text</span><span class="token punctuation">,</span><span class="token variable">$match</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//印出match[0]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token variable">$match</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="結合" tabindex="-1"><a class="header-anchor" href="#結合" aria-hidden="true">#</a> 結合</h2>
<div class="language-php ext-php line-numbers-mode"><pre v-pre class="language-php"><code><span class="token comment">//取得指定位址的內容，並儲存至text</span>
<span class="token variable">$text</span><span class="token operator">=</span><span class="token function">file_get_contents</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'https://alan-zl.github.io/Blogs/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>   

<span class="token comment">//取出div標籤且id為PostContent的內容，並儲存至陣列match</span>
<span class="token function">preg_match</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'/&lt;div[^>]*id="PostContent"[^>]*>(.*?) &lt;\/div>/si'</span><span class="token punctuation">,</span><span class="token variable">$text</span><span class="token punctuation">,</span><span class="token variable">$match</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  

<span class="token comment">//取得第一個img標籤，並儲存至陣列match2</span>
<span class="token function">preg_match</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'/&lt;img[^>]*>/Ui'</span><span class="token punctuation">,</span> <span class="token variable">$match</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token variable">$match2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//印出match2[0]</span>
<span class="token function">print_r</span><span class="token punctuation">(</span><span class="token variable">$match2</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="參考" tabindex="-1"><a class="header-anchor" href="#參考" aria-hidden="true">#</a> 參考</h2>
<h6 id="king的幸福國度" tabindex="-1"><a class="header-anchor" href="#king的幸福國度" aria-hidden="true">#</a> <a href="https://kingjoy1235.pixnet.net/blog/post/28598212" target="_blank" rel="noopener noreferrer">King的幸福國度</a></h6>
</template>
